### ISSUE TITLE
Horizontal scrolling causes exceptions

### ISSUE THREAD

**Issue by jonny7737** [adrianjagielak/flutter_markdown_selectionarea#2]
I am writing a desktop app.

When my app shows a code sample in markdown and the code has lines that are longer than the width of the enclosing container, any horizontal scrolling of the code block throws hundreds of exceptions.

The exception is;

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.

Any insight into the possible cause?

**Comment by adrianjagielak** [comment]
You must set `primary: false` in your scroll view

**Comment by jonny7737** [comment]
Unfortunately, this did not solve the problem.

**Comment by jonny7737** [comment]
I changed primary to true and controller to null. That work.  Thank you for your help. I really appreciate your work.
