### ISSUE TITLE
Possible to update this to 0.6.17+1 Flutter Markdown.

### ISSUE THREAD

**Issue by macwilko** [adrianjagielak/flutter_markdown_selectionarea#3]
Thank-you Adrian for this fix, have you considered trying to merge this into the official Markdown Package? 

I'de like to upgrade to the latest 0.6.17+1 but I need SelectionArea also >.<

**Comment by adrianjagielak** [comment]
@mattsrobot I don’t have time to bother with creating PR/documentation/tests for this to be merged into the official Flutter Markdown package but i can update my package to 0.6.17+1 with the new markdown changes later today

**Comment by macwilko** [comment]
I completely understand, really appreciate your work here ⭐️⭐️⭐️

**Comment by adrianjagielak** [comment]
@mattsrobot [updated to 0.6.17+1](https://pub.dev/packages/flutter_markdown_selectionarea/changelog)
