### ISSUE TITLE
breaks onTapText functionality

### ISSUE THREAD

**Issue by galacticgibbon** [adrianjagielak/flutter_markdown_selectionarea#4]
onTapText is broken

Usecase: Different functionality based on tapping/dragging.

For instance, I want to tap to open an editor, and drag to select text.

**Comment by adrianjagielak** [comment]
wrap it with GestureDetector and use onTap like this:

```dart
return SelectionArea(
  child: GestureDetector(
    onTap: () {
      print('tapped');
    },
    child: MarkdownBody(
      data: 'markdown text',
    ),
  ),
);
```
